name: Pull Request Title Check
on:
  pull_request:
    types: [opened, edited, synchronize]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  pull-requests: read
jobs:
  pull-request-title-check:
    runs-on: depot-ubuntu-24.04
    timeout-minutes: 5
    container:
      image: node:24-slim
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Check pull request title
        run: node ./scripts/pull-request-title-check.ts
